/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* Last updated: 2025-01-11 - Clean deployment with single server function */

export const projectId = "ywephsepixgcdxdlxwmt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3ZXBoc2VwaXhnY2R4ZGx4d210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NDA0MDQsImV4cCI6MjA3NzExNjQwNH0.TdWUKj0Ob988nxKPniVK2cB6pfwCvHBfY1F0WuvUUZE"
